name: Build and Release Node.js App with Docker

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: echo "running unit test"

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Match label
      id: bump
      uses: zwaldowski/match-label-action@v1
      with:
        allowed: major, minor, patch

    - name: Bump version 
      id: semver
      uses: leovs09/semver-release-action@v3
      with:
        version: "1.0.0"
        bump: ${{ steps.bump.outputs.match }}
        github_token: ${{ secrets.SEMVER_TOKEN }}

    - name: Store New Version
      run: |
        echo "NEW_VERSION=${{ steps.semver.outputs.version }}" >> $GITHUB_ENV
        
    - name: Use New Version
      run: |
        echo "The new version is: $NEW_VERSION"

    
